In [1]:
import numpy as np
import pandas as pd

In [3]:
df1=pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B3'],
    'C':['C0','C1','C3']
})
df2=pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5']
})

In [5]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B3  C3

In [6]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [13]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B3  C3
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [14]:
#if i want to write first df2 then wrrite df1

In [16]:
pd.concat([df2,df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B3  C3

In [17]:
pd.concat([df1,df2,axis=0])

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (4028330107.py, line 1)